### ISSUE TITLE
SIGSEG when connecting lines with an overlay on the red area 

### ISSUE THREAD

**Issue by gavr123456789** [StefanSalewski/SDT#1]
https://user-images.githubusercontent.com/30507409/127375369-589cb4e9-3737-48cb-9715-5d19760042ce.mp4

If connecting a line, end it when the other line in the "red focus" crashes.

**Comment by StefanSalewski** [comment]
Thanks for testing. Of course I know that the app is still full of bugs, but it is good to know that someone other can launch it at all. Nice video. In the last weeks I considered making a video myself -- not only to show functionality to others, but also that I do not forget how to use it when I have to take a longer break. Unfortunately the Gnome screen recording of my Gentoo Linux box does not work, you may have seen my thread about that on the Gnome forum. Really sad, should be my first video, and one of the rare cases where a video would make sense, and it does not work. And absolutely no error message.

Yesterday I made changing the grid working, and I made the Grid label a button, to select between big and small grid. Your bug should be related to zero length lines, there is no code to check for that currently. I may add it this evening, and I will start writing some docs for usage.

**Comment by StefanSalewski** [comment]
This bug has been replaced by many others now.
